### ISSUE TITLE
improve factor handling

### ISSUE THREAD

**Issue by rhijmans** [tgoodbody/sgsR#18]
Hi, In `sample_strat` you have 

```
    samples <- samples %>%
      dplyr::left_join(samples, sraster_cats, by = c("strata" = "value"))
``` 
Where 

```
    sraster_cats <- cats(sraster) %>% 
      as.data.frame()
``` 

Which assumes that the name of the first column of `sraster_cats` is always "value". That is not correct. I think you should either use the actual column name, or, perhaps easiest, change it to "value" like this.

```
    sraster_cats <- cats(sraster) %>% 
      as.data.frame()
   colnames(sraster_cats)[1] <- "value"
``` 

I found this because "sgsR" triggered a reverse dependency error with "terra". I was able to get rid of that error for your example; but your assumption about the column name is still wrong.

**Comment by tgoodbody** [comment]
Hi @rhijmans 

Thanks for letting me know about this and sorry for taking up your time.

Ive used your code suggestion and tested outputs with no errors.

Appreciate your time

T

```
  if(!is.null(terra::cats(sraster)[[1]])){
    message("'sraster' has factor values. Converting to allow mapping.")
    
    #--- change suggested by R Hijmans ---#
    sraster_cats <- cats(sraster) %>% 
      as.data.frame()
    colnames(sraster_cats)[1] <- "value"
    
  }
  ```
