### ISSUE TITLE
terra interface

### ISSUE THREAD

**Issue by rhijmans** [tgoodbody/sgsR#31]
In `sgsR::strat_map`  you have 

```
if (isFALSE(sraster@ptr$hasValues)) {
```

That breaks with the development version of terra. The @ptr$ methods are not really safe for use in other packages. Can you use the "official" interface instead? In this case that could be:

```
if (isFALSE(hasValues(sraster)) {
```

Thanks!

**Comment by tgoodbody** [comment]
Thanks for letting me know! Will update now.
