### ISSUE TITLE
Compute slope distance

### ISSUE THREAD

**Issue by spono** [tgoodbody/sgsR#32]
Hi,
using `calculate_distance` seems to take a bit of time to compute a distance that is/looks a basic "buffered" distance.
A possible enhancement to implement would be allowing to compute the slope distance, a solution that becomes very handy in the case of steep mountainous areas...and faster from a computational point of view.
Differences are not huge but it gives to the function a broader application. Indeed, I think it works well not only for sending out the field crews but also in the evaluations related to the possible harvesting systems (i.e. cable cranes) and the remote assessment of the potential wood volume retractable by each system.

A possibility would be to implement it as follows:

```
  # add parameter to the function
  slope.correction = FALSE
```

```
  if( !isTrue(slope.correction) ){
    dist2access <- terra::distance(raster[[1]], access)
  } else {
    slopeDist <- terra::terrain(dtm, v="slope", unit="radians", neighbors=8)
    
    slopeDist <-  terra::res(slopeDist)[1] / cos(slopeDist)
    
    access$value <- 0
    
    access <- terra::rasterize( access, slopeDist, field="value", background=1 ) # values=0
    
    slopeDist <- slopeDist * access
    
    dist2access <- terra::costDist( slopeDist, target=0, scale=res(slopeDist)[1], maxiter=50)
  }
```

**Comment by tgoodbody** [comment]
Thanks for this suggestion. Will look into it more and update you next week probably! @spono
