### ISSUE TITLE
mindist option for adding to existing samples

### ISSUE THREAD

**Issue by jfprieur** [tgoodbody/sgsR#34]
Hello, perhaps I am looking at it the wrong way but I was wondering if there is a mindist option equivalent when adding to existing samples. I created a first set of plot candidates using sample_strat and used the mindisyt parameter.

I now want to add some more sample plots but it seems those functions (sample_existing, sample_ahels) do not have the mindist option.

Is there a way to specify a minimal distance between candidates when adding to an existing plot network?

**Comment by tgoodbody** [comment]
Hi JF,

`mindist` is applied iteratively for samples, which increases processing overhead. One could add it to `sample_ahels()` but it would likely increase require processing time substantially. I dont have capacity to add new features to `sgsR` currently but welcome any pull requests with justifications. My advice would be to add more samples than needed and then filter them using a distance threshold.
